### ISSUE TITLE
请问是否还缺少jd_assistant，您另外一个项目的可以用吗

### ISSUE THREAD

**Issue by Dlian-Zero** [SSJACK8582/jd_ql_assistant#3]
Traceback (most recent call last):
  File "jd.py", line 35, in <module>
    jd_assistant.main(args.area, args.sku_ids, buy_time, args.mode, account_list)
AttributeError: module 'jd_assistant' has no attribute 'main'

用了您上一个项目的部分文件

**Comment by SSJACK8582** [comment]
请看Releases

**Comment by 5jwoj** [comment]
请问商品ID如何获取？

**Comment by Dlian-Zero** [comment]
> 请问商品ID如何获取？

复制商品链接可以看到

**Comment by Dlian-Zero** [comment]
> 请看Releases

[jd_assistant.cpython-310-x86_64-linux-gnu.so]这个文件直接放进去青龙根目录吗
